# Generated by Django 4.1.4 on 2022-12-25 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_assistant", "0002_pythondocstring"),
    ]

    operations = [
        migrations.CreateModel(
            name="FixedCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code_snippet", models.TextField()),
                ("language", models.CharField(max_length=50)),
                ("fixed_code", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
