# Generated by Django 4.1.4 on 2022-12-25 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_assistant", "0004_alter_fixedcode_fixed_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fixedcode",
            name="fixed_code",
            field=models.TextField(),
        ),
    ]
