# Generated by Django 4.1.4 on 2022-12-31 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_assistant", "0006_timecomplexity"),
    ]

    operations = [
        migrations.AddField(
            model_name="timecomplexity",
            name="time_complexity",
            field=models.TextField(default="O(1)"),
        ),
    ]
