# Generated by Django 4.1.4 on 2022-12-31 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_assistant", "0008_delete_timecomplexity"),
    ]

    operations = [
        migrations.CreateModel(
            name="TimeComplexity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code_snippet", models.TextField()),
                ("time_complexity", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
